sonar.projectKey=crud-frontend
sonar.projectName=Three Tier CRUD Frontend
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src/tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,dist/**,coverage/**,public/**
sonar.test.exclusions=node_modules/**,dist/**,coverage/**

sonar.sourceEncoding=UTF-8
