sonar.projectKey=crud-frontend
sonar.projectName=Three Tier CRUD Frontend
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src/tests
sonar.test.inclusions=src/tests/**

sonar.exclusions=node_modules/**,dist/**,coverage/**,public/**,src/tests/**
sonar.test.exclusions=node_modules/**,dist/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
